### ISSUE TITLE
Boxplot data in sqllite

### ISSUE THREAD

**Issue by stevemmarshall** [cancergenetics/cancergd#1]
Hi

Looking at the sqlite tables, I noticed that the boxplot data column isn't in a separate normalized table. I assume this was done for visualization and storage purposes. Do you save that file anywhere?

thanks
steve

**Comment by colmr** [comment]
Hi Steve,

No we don't save it anywhere other than as a column in the database. Obviously you can export it from the SQLite DB if you have a use for it. You can access the data (in a nicer format) for individual entries using the UI - click to view a boxplot and then select "Download boxplot as : csv". 

As you suggest - we primarily store these for visualisation purposes. In earlier releases we stored images but we switched to storing the values so that we could draw the boxplots in an interactive / dynamic fashion. 

Best,

Colm
